name: Generate PAC File

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [master]
    paths:
      - "user-rules.txt"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      # pac-proxy 配置
      C1: "PROXY 127.0.0.1:1080; SOCKS5 127.0.0.1:1080"
      # user-rule-from 配置
      C2: "./user-rules.txt"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Setup generate tools
        uses: BSFishy/pip-action@v1
        with:
          packages: genpac

      - name: Run genpac
        run: genpac --format "pac" --pac-proxy "$C1" --user-rule-from $C2 > pac.txt

      - name: Get current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit and push
        uses: EndBug/add-and-commit@v4
        with:
          message: update pac.txt ${{ steps.date.outputs.date }}
          add: "*.txt"
          author_name: "actions-user"
          author_email: "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
